[package]
name = "corollary"
version = "0.3.1"
authors = [
  "Tim Ryan <tim@timryan.org>",
  "Paul Collier <paul@paulcollier.ca>",
  "xiaoniu <hzmxn@mail.ustc.edu.cn>"
]
description = "Cross-compiles Haskell into Rust."
repository = "http://github.com/tcr/corrode-but-in-rust"
homepage = "http://github.com/tcr/corrode-but-in-rust"
license = "MIT/Apache-2.0"

[dependencies]
clap = "2.24"
errln = "0.1.0"
error-chain = "0.10"
hex = "0.2.0"
lalrpop-util = "0.12.5"
maplit = "0.1.4"
regex = "0.2.1"
tempdir = "0.3"
walkdir = "1"
Inflector = "0.10.0"
matches = "0.1.4"
iflet = "0.1.0"
parser-haskell = "0.2.1"

[patch.crates-io]
parser-haskell = { path = "../parser-haskell/" }
